# NumPy  SciPy

In [4]:
import numpy as np

## Задание 1 ★★☆

Разбейте массив на убывающие подмассивы.  
Подсказка: np.diff()  
Используйте библиотеку `numpy`, не используйте циклы.

In [5]:
def function_1(arr):
    return np.split(arr, np.where(np.diff(arr)>=0)[0]+1)

Проверка

In [6]:
len(function_1([3, 2, 1, 4, 5, 2, 0, 2, 4, 1])) == 5

True

In [7]:
np.random.seed(42)
len(function_1(np.random.randint(-10, 10, size=20))) == 9.

True

In [8]:
np.random.seed(42)
len(function_1(np.random.randint(-10, 100, size=10))) == 4

True

Значение для формы

In [9]:
np.random.seed(21)
a = np.random.uniform(0, 3000, size=1000)
print(len(function_1(a)))

505


## Задание 2 ★★☆

Дан массив arr, необходимо найти среднее значение внутри групп, группа определена массивом g. Например, для  
`arr = [4, 2, 1, 5, 2, 5, 1, 3]` и   
`g =   [0, 1, 1, 0, 1, 0, 1, 0]` (4 относится к группе 0, 2 к группе 1 и т. д.)   
Средние по группам: `[4.25, 1.5]`  
Подсказка: `np.bincount()`   
Используйте библиотеку `numpy`, не используйте циклы.

In [12]:
g =   [0, 1, 1, 0, 1, 0, 1, 0]
arr = [4, 2, 1, 5, 2, 5, 1, 3]

In [17]:
def function_2(arr, g):
    return np.bincount(g,  weights=arr)/np.bincount(g)

Проверочный код

In [18]:
all(function_2(np.array([4, 2, 1, 5, 2, 5, 1, 3]), np.array([0, 1, 1, 0, 1, 0, 1, 0])) == [4.25, 1.5])

True

In [19]:
np.random.seed(42)
all(function_2(np.random.randint(0, 25, size=10), np.random.randint(0, 3, size=10)) == [12., 15.2, 10.])

True

In [20]:
np.random.seed(42)
all(function_2(np.random.randint(0, 100, size=10), np.random.randint(0, 4, size=10)) == [89., 78., 20., 54.])

True

Значение для формы

In [21]:
np.random.seed(21)
a = np.random.uniform(0, 3000, size=1000)
g = np.random.randint(0, 20, 1000)
print(np.round(function_2(a, g).sum(), 4))

30021.8043


## Задание 3 ★★★

Предположим нам даны две выборки-матрицы: обучающая X_train (размер l1 x n) и тестовая X_test (размер l2 x n), каждая строка в матрице - это вектор, описывающий объект в n-мерном пространстве. Допустим, что в ходе некоторой задачи потребовалось вычислить расстояние между векторами из тестовой и обучающей выборки. То есть для каждой строки-вектора из тестовой выборки нужно найти расстояние до каждого вектора из обучающей, таким образом мы получим матрицу dist размера l1 x l2.   

В этом задании необходимо получить матрицу расстояний dist, **не используя циклы**.
Для начала, попробуйте это сделать через два цикла и сравните эффективность с конечной реализацией через numpy.  

In [38]:
np.hypot(*(X_train.reshape(2, -1) - X_test.reshape(2, -1)))

ValueError: operands could not be broadcast together with shapes (2,90000000) (2,1500000) 

In [35]:
X_test.reshape(2, -1).shape

(2, 1500000)

In [45]:
from scipy.spatial.distance import cdist
out = cdist(X_train,X_test)

In [53]:
np.linalg.norm(X_train[0]-X_test[0])

22.137696894791475

In [47]:
out

array([[22.13769689, 22.6237708 , 22.47632644, ..., 22.72537546,
        22.74303107, 22.15402209],
       [22.33341771, 22.5405476 , 22.75474307, ..., 22.01215805,
        22.60452331, 22.06264011],
       [22.24094   , 22.00046293, 21.91948332, ..., 22.08535327,
        22.29969455, 22.35703421],
       ...,
       [22.35669937, 22.46473762, 22.74392976, ..., 22.07000357,
        22.27903365, 22.20818131],
       [22.28549441, 22.24603046, 22.67908373, ..., 22.09411892,
        22.65341851, 22.24750325],
       [22.45707796, 22.65748442, 22.49964285, ..., 22.59302618,
        22.76402098, 22.42974159]])

In [14]:
def function_3(X_train, X_test):
    # TODO

Значение для формы

In [54]:
%%time
# np.random.seed(42)
# X_train, X_test = np.random.rand(60000, 3000), np.random.rand(1000, 3000)
# dist = function_3(X_train, X_test)
print(np.round(out.sum(), 4))

1341747083.8534
Wall time: 68 ms


## Задание 4 ★☆☆

Реализуйте функцию вычисляющую приближенную матрицу $X_k$  для матрицы $X$ заданного ранга $k$ по норме Фробениуса.   
Подсказка:   
см. семнар SciPy  
scipy.linalg.svd  

In [192]:
import scipy
from sklearn.decomposition import PCA
from scipy.linalg import svd

In [291]:
def function_4(X, k):
    u, s, vh = svd(X)
    print(np.diag(s)[:,:k])
    print(u)
    return np.dot(u @ np.diag(s)[:,:k], vh[:k,:])

In [301]:
X_k = function_4(X, 1)

[[22.36510117]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[-0.5337231   0.10214081 -0.3083312   0.78079369]
 [-0.58486967 -0.52710856 -0.3838606  -0.48242623]
 [-0.46326037  0.79364259  0.0965698  -0.38235526]
 [-0.39806652 -0.28610357  0.86501861  0.106914  ]]


In [302]:
X_k

array([[6.11017561, 3.42212454, 7.08494351, 4.88134255, 4.40651697],
       [6.69571249, 3.75006604, 7.7638922 , 5.34912061, 4.82879259],
       [5.30350326, 2.97033176, 6.14958119, 4.23690214, 3.82476358],
       [4.55715022, 2.552322  , 5.28416104, 3.64065007, 3.28651107]])

In [278]:
np.linalg.matrix_rank(X_k) == 3

True

In [279]:
X,X_k

(array([[6, 3, 7, 4, 6],
        [9, 2, 6, 7, 4],
        [3, 7, 7, 2, 5],
        [4, 1, 7, 5, 1]]),
 array([[6.29395613, 3.93074059, 6.49802023, 4.37786463, 5.25809381],
        [8.81837437, 1.4249266 , 6.31015646, 6.76653012, 4.45839895],
        [2.85604946, 6.54421563, 7.24581987, 1.8149594 , 5.36331202],
        [4.04025138, 1.12744621, 6.93126396, 5.05174097, 0.89841086]]))

In [280]:
scipy.linalg.norm(X - X_k)

1.76440345368773

Проверка

In [289]:
np.random.seed(42)
X = np.random.randint(0, 10, size=(4, 5))
(scipy.linalg.norm(X - X_k) < 2 and np.linalg.matrix_rank(X_k) == 3)

ValueError: operands could not be broadcast together with shapes (4,5) (100,150) 

In [282]:
np.random.seed(42)
X = np.random.randint(0, 10, size=(4, 5))
X_k = function_4(X, 4)
print(scipy.linalg.norm(X - X_k))
print(X)
print(X_k)
(scipy.linalg.norm(X - X_k) < 1e-10 and np.linalg.matrix_rank(X_k) == 4)

9.454512220249963e-15
[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]]
[[6. 3. 7. 4. 6.]
 [9. 2. 6. 7. 4.]
 [3. 7. 7. 2. 5.]
 [4. 1. 7. 5. 1.]]


True

Значение для формы

In [283]:
np.random.seed(42)
X = np.random.randint(0, 10, size=(100, 150))
X_k = function_4(X, 40)
print(np.round(scipy.linalg.norm(X - X_k), 3) * np.linalg.matrix_rank(X_k))

7279.84


## Задание 5 ★★☆

Найдите тангенс угла наклона прямой, такой что максимальное расстояние от точек $X$ до прямой минимально. Cчитайте, что прямая проходит через начало координат.

In [306]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LinearRegression
data = load_breast_cancer()
X = data.data[:, :2]

In [309]:
lr = LinearRegression()
lr.fit(X[:,0].reshape(-1, 1),X[:,1].reshape(-1, 1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [311]:
lr.coef_

array([[0.39516975]])

In [316]:
def function_5(points):
    lr = LinearRegression()
    lr.fit(X[:,0].reshape(-1, 1),X[:,1].reshape(-1, 1))
    return lr.coef_[0][0]
    

Значение для формы

In [317]:
print(round(function_5(X), 3))

0.395
